/*        
        ➪：短信群发

        ★：解锁永久🆅🅸🅿

        𖣘： @𝙍𝙣𝙞𝙠➏➏➏

𒊹𒊹𒊹𒊹𒊹𒊹𒊹𒊹𒊹𒊹𒊹𒊹𒊹𒊹𒊹𒊹𒊹𒊹𒊹𒊹𒊹

[rewrite_local] 

^https?:\/\/api\.revenuecat\.com\/v1\/subscribers\/
url script-response-body https://raw.githubusercontent.com/Rnik666/YJTJS/main/DXQF.JS

[MITM]
hostname = api.revenuecat.com


*/
{
  "request_date_ms" : 1760889378502,
  "request_date" : "2025-10-19T15:56:18Z",
  "subscriber" : {
    "non_subscriptions" : {
      "com.bokhary.lazygroup.lazygrouppro" : [
        {
          "is_sandbox" : false,
          "ownership_type" : "PURCHASED",
          "id" : "888888888",
          "expires_date" : "2099-09-09T09:09:09Z",
          "original_purchase_date" : "2024-09-09T09:09:09Z",
          "store_transaction_id" : "490001314520000",
          "purchase_date" : "2024-09-09T09:09:09Z",
          "store" : "app_store"
        }
      ],
      "com.bokhary.lazygroup.monthlyprosubscription" : [
        {
          "is_sandbox" : false,
          "ownership_type" : "PURCHASED",
          "id" : "888888888",
          "expires_date" : "2099-09-09T09:09:09Z",
          "original_purchase_date" : "2024-09-09T09:09:09Z",
          "store_transaction_id" : "490001314520000",
          "purchase_date" : "2024-09-09T09:09:09Z",
          "store" : "app_store"
        }
      ],
      "com.bokhary.lazygroup.yearlyprosubscription" : [
        {
          "is_sandbox" : false,
          "ownership_type" : "PURCHASED",
          "id" : "888888888",
          "expires_date" : "2099-09-09T09:09:09Z",
          "original_purchase_date" : "2024-09-09T09:09:09Z",
          "store_transaction_id" : "490001314520000",
          "purchase_date" : "2024-09-09T09:09:09Z",
          "store" : "app_store"
        }
      ]
    },
    "first_seen" : "2025-10-19T15:56:18Z",
    "original_application_version" : null,
    "other_purchases" : {
      "com.bokhary.lazygroup.lazygrouppro" : {
        "expires_date" : "2099-09-09T09:09:09Z",
        "purchase_date" : "2024-09-09T09:09:09Z"
      },
      "com.bokhary.lazygroup.monthlyprosubscription" : {
        "expires_date" : "2099-09-09T09:09:09Z",
        "purchase_date" : "2024-09-09T09:09:09Z"
      },
      "com.bokhary.lazygroup.yearlyprosubscription" : {
        "expires_date" : "2099-09-09T09:09:09Z",
        "purchase_date" : "2024-09-09T09:09:09Z"
      }
    },
    "management_url" : null,
    "subscriptions" : {
      "com.bokhary.lazygroup.lazygrouppro" : {
        "is_sandbox" : false,
        "ownership_type" : "PURCHASED",
        "expires_date" : "2099-09-09T09:09:09Z",
        "original_purchase_date" : "2024-09-09T09:09:09Z",
        "store_transaction_id" : "490001314520000",
        "purchase_date" : "2024-09-09T09:09:09Z",
        "store" : "app_store"
      },
      "com.bokhary.lazygroup.monthlyprosubscription" : {
        "is_sandbox" : false,
        "ownership_type" : "PURCHASED",
        "expires_date" : "2099-09-09T09:09:09Z",
        "original_purchase_date" : "2024-09-09T09:09:09Z",
        "store_transaction_id" : "490001314520000",
        "purchase_date" : "2024-09-09T09:09:09Z",
        "store" : "app_store"
      },
      "com.bokhary.lazygroup.yearlyprosubscription" : {
        "is_sandbox" : false,
        "ownership_type" : "PURCHASED",
        "expires_date" : "2099-09-09T09:09:09Z",
        "original_purchase_date" : "2024-09-09T09:09:09Z",
        "store_transaction_id" : "490001314520000",
        "purchase_date" : "2024-09-09T09:09:09Z",
        "store" : "app_store"
      }
    },
    "entitlements" : {
      "lazyGroupYearlySubscription" : {
        "expires_date" : "2099-09-09T09:09:09Z",
        "product_identifier" : "com.bokhary.lazygroup.yearlyprosubscription",
        "purchase_date" : "2024-09-09T09:09:09Z"
      },
      "lazyGroupPro" : {
        "expires_date" : "2099-09-09T09:09:09Z",
        "product_identifier" : "com.bokhary.lazygroup.lazygrouppro",
        "purchase_date" : "2024-09-09T09:09:09Z"
      },
      "lazyGroupMonthlySubscription" : {
        "expires_date" : "2099-09-09T09:09:09Z",
        "product_identifier" : "com.bokhary.lazygroup.monthlyprosubscription",
        "purchase_date" : "2024-09-09T09:09:09Z"
      }
    },
    "original_purchase_date" : null,
    "original_app_user_id" : "$RCAnonymousID:0de4149771cc45869e4d9f40d6b66df4",
    "last_seen" : "2025-10-19T15:56:18Z"
  }
}
